[package]
name = "rust_add"
version = "0.1.0"
authors = ["Jayson Falkner <jfalkner@gmail.com>"]
edition = "2018"
description = "Example from RustCUDA quickstart: https://github.com/bheisler/RustaCUDA#quickstart"


[dependencies]
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
